### PR TITLE
Enable testing on Windows

### PR DESCRIPTION
**Pull request by ppolewicz**

### CODE REVIEW

**Comment by ppolewicz** [comment]
Python 3.5.2:
```
======================================================================
ERROR: test_slash_sorting (test.test_sync.TestLocalFolder)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\b2-command-line-tool\test\test_sync.py", line 71, in test_slash_sorting
    folder = self._prepare_folder(tmpdir)
  File "C:\projects\b2-command-line-tool\test\test_sync.py", line 61, in _prepare_folder
    self._create_files(root_dir, self.NAMES)
  File "C:\projects\b2-command-line-tool\test\test_sync.py", line 58, in _create_files
    write_file(full_path, b'')
  File "C:\projects\b2-command-line-tool\test\test_sync.py", line 40, in write_file
    os.makedirs(parent)
  File "C:\Python35-x64\lib\os.py", line 241, in makedirs
    mkdir(name, mode)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\tmppfu5j11b\\hello/a'
----------------------------------------------------------------------
```

Python 2.6.6:
```
======================================================================
ERROR: test_sync (test.test_console_tool.TestConsoleTool)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\b2-command-line-tool\test\test_console_tool.py", line 371, in test_sync
    with TempDir() as temp_dir:
  File "C:\projects\b2-command-line-tool\b2\utils.py", line 191, in __enter__
    self.dirpath = six.u(tempfile.mkdtemp())
  File "C:\Python266\lib\site-packages\six.py", line 647, in u
    return unicode(s.replace(r'\\', r'\\\\'), "unicode_escape")
UnicodeDecodeError: 'unicodeescape' codec can't decode bytes in position 2-4: truncated \uXXXX escape
-------------------- >> begin captured logging << --------------------
b2.console_tool: INFO: // ========================================  0.6.7   ======================================== \\
b2.console_tool: DEBUG: platform is Windows-post2008Server-6.2.9200
b2.console_tool: DEBUG: Python version is CPython 2.6.6 (r266:84297, Aug 24 2010, 18:46:32) [MSC v.1500 32 bit (Intel)]
b2.console_tool: DEBUG: locale is ('en_US', 'cp1252')
b2.console_tool: DEBUG: filesystem encoding is mbcs
b2.console_tool: INFO: starting command [b2.console_tool.AuthorizeAccount] (arguments hidden)
b2.console_tool: INFO: // ========================================  0.6.7   ======================================== \\
b2.console_tool: DEBUG: platform is Windows-post2008Server-6.2.9200
b2.console_tool: DEBUG: Python version is CPython 2.6.6 (r266:84297, Aug 24 2010, 18:46:32) [MSC v.1500 32 bit (Intel)]
b2.console_tool: DEBUG: locale is ('en_US', 'cp1252')
b2.console_tool: DEBUG: filesystem encoding is mbcs
b2.console_tool: INFO: starting command [b2.console_tool.CreateBucket] with arguments: ['b2', 'create_bucket', 'my-bucket', 'allPublic']
--------------------- >> end captured logging << ---------------------
======================================================================
```

And this one on both:
```
======================================================================
ERROR: Tests converting from a JSON account info file, which is what version
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\b2-command-line-tool\test\test_account_info.py", line 124, in test_convert_from_json
    account_info = self._make_info()
  File "C:\projects\b2-command-line-tool\test\test_account_info.py", line 192, in _make_info
    return SqliteAccountInfo(file_name=self.db_path)
  File "C:\projects\b2-command-line-tool\b2\account_info\sqlite_account_info.py", line 38, in __init__
    self._validate_database()
  File "C:\projects\b2-command-line-tool\b2\account_info\sqlite_account_info.py", line 74, in _validate_database
    os.unlink(self.filename)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\tmp_b2_tests_test.test_account_info.TestSqliteAccountInfo.test_convert_from_json__oz7htkj2'
-------------------- >> begin captured stdout << ---------------------
using C:\Users\appveyor\AppData\Local\Temp\1\tmp_b2_tests_test.test_account_info.TestSqliteAccountInfo.test_convert_from_json__oz7htkj2
--------------------- >> end captured stdout << ----------------------
======================================================================
```

**Comment by ppolewicz** [comment]
other issues need to be debugged using a Windows machine

**Comment by bwbeach** [comment]
I'm heading to Backblaze HQ today.  If it can wait, I can debug Windows issues on my Windows machine when I get home next week.

**Comment by ppolewicz** [comment]
It can wait.

**Comment by bwbeach** [comment]
I no longer have a Windows machine for testing.  What's needed on this PR?

**Comment by ppolewicz** [comment]
This has become a bit more complicated now that we've split the sdk off. We should run the tests on both the CLI and SDK, but before we configure appveyor (or maybe Azure?) for it, first we should make sure it actually works on Windows.

Most likely the changes that I did here need to be rebased from 2016 to 2020, then any remaining issues that will come up after running tests must be hunted down and fixed.

I vaguely remember there was a complex issue with sync tests on Windows (not sync itself, just the tests) like a year ago, but we might have fixed it already.

**Comment by mlech-reef** [comment]
I believe this one is now covered by #650. There, we run exactly the same test suite on a matrix of 3 OSes and 6 Python versions.

**Comment by ppolewicz** [comment]
yes, #650 is much better

**Pull request closed without merging**
