### PR TITLE
Library layer - first part

### PR DESCRIPTION
**Pull request by ppolewicz**
This PR is WIP (created for easy early review). Please do not merge it before it is ready.

This will eventually implement #4.

Task list:
- [x] Create library access skeleton
- [x] Implement B2Api.list_buckets()
- [x] Implement B2Api.get_bucket_by_id()
- [x] Implement B2Api.create_bucket()
- [x] Implement B2Api.delete_bucket()
- [x] Implement B2Api.make_url() 
- [x] Add api to bucket constructor 
- [x] Implement AbstractBucket.hide_file() 
- [x] drop AbstractBucket .getUploadUrl() (accidentally copied from java)
- [x] implement B2Api.delete_file_version()
- [x] implement bucket.set_type()
- [x] implement InMemoryCache.save_bucket()
- [x] remove FileInfo
- [x] implement clear_account (?)
- [x] rethink BucketType enum
- [x] rething AbstractBucket class hierarchy
- [ ] implement api.download_file_by_id()
- [ ] implement AbstractBucket.download_file_by_name()
- [ ] implement bucket.list_file_names()
- [ ] implement bucket.list_file_versions()
- [ ] implement bucket.upload_file()
- [ ] refactor "400 bad request" exception handling
- [ ] remove ConsoleTool.info temporary property
- [ ] drop or move v0.3.x functions

Unfinished items will be done in another PR

### CODE REVIEW

**Comment by ppolewicz** [comment]
@bwbeach please review to confirm that our views are still aligned. `list_buckets` now has a library interface and a console command handler interface which depends on the library interface.

Console version should not be affected.

Example usage of library:
```python
>>> import b2
>>> api = b2.B2Api(b2.StoredAccountInfo())
>>> for b in api.list_buckets():
...     print b.name
... 
test234
>>> b = api.get_bucket_by_name('foobar')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "b2.py", line 305, in get_bucket_by_name
    raise NonExistentBucket(bucket_name)
b2.NonExistentBucket: No such bucket: foobar
>>>
```

**Comment by ppolewicz** [comment]
@bwbeach this is blocking for me: I don't want to put a few dozen hours into it without first making sure that my way of doing it is fine for you (and will get merged). Could you please take a quick look at it by tomorrow EOD?

**Comment by bwbeach** [comment]
Pawel,

Sorry for the delay.  Just got back traveling this weekend.

Your changes look good, and I like the direction you're taking.  Just a few comments:

What's the reason for mapping bucket types to 1001 and 1002?  It might be easier when debugging just to use the strings names internally.
I like the exception hierarchy.
I don't yet see where you're going with the class hierarchy AbstractBucket/UnknownTypeBucket/Bucket.
The layering is looking good.
Your coding style is clean and readable.

- BrianB

**Comment by ppolewicz** [comment]
The thing with bucket types is a generic pattern for enum in python. You might be right, it may not be very useful here, I'll make a note to look at it again at the end and remove it if it is still not useful.

Bucket types is a defense against user having to check if fields of bucket are None everywhere, so that any operation on bucket is contained in the class rather than splattered in every place someone needs to use it... However it is clear that you are working with b2 much longer than me - I can not think of any operations that would need to be extracted like that. I added a note to review and simplify that as well.

Than you very much for the review, now I can proceed.

**Comment by ppolewicz** [comment]
@bwbeach 
```python
api = b2.B2Api(b2.StoredAccountInfo())
bucket = api.get_bucket_by_name('foobar')
api.delete_bucket(bucket)
```
or
```python
api = b2.B2Api(b2.StoredAccountInfo())
bucket = api.get_bucket_by_name('foobar')
bucket.delete()
```

? I think the first version is better, because `bucket.delete()` might be confused between deleting a file and deleting a bucket, while `api.delete_bucket(bucket)` can not be confused with anything.

**Comment by bwbeach** [comment]
> api = b2.B2Api(b2.StoredAccountInfo())
> bucket = api.get_bucket_by_name('foobar')
> api.delete_bucket(bucket)
> or
> 
> api = b2.B2Api(b2.StoredAccountInfo())
> bucket = api.get_bucket_by_name('foobar')
> bucket.delete()
> ? I think the first version is better, because bucket.delete() might be confused between deleting a file and deleting a bucket, while api.delete_bucket(bucket) can not be confused with anything.
> 
I agree.  I think api.delete_bucket(bucket) is clearer, and I like keeping the name "delete_bucket" consistent with the B2 web API.

- BrianB

**Comment by ppolewicz** [comment]
@bwbeach why does `b2_delete_file_version` api call accept a file name parameter? Isn't the file id sufficient to identify a file in the b2 storage?

**Comment by bwbeach** [comment]
Passing the file name into `b2_delete_file_version` makes the implementation easier.  It's quite possible to do without it, but saves us a step, and makes things faster, if the name is passed in.  We are considering removing that requirement in a future version of the API.

**Comment by ppolewicz** [comment]
@bwbeach #20 modifies the same code that I am going to modify. As you intend to accept #20, I'll merge it when working on #11 to avoid a massive conflict.

**Comment by ppolewicz** [comment]
@bwbeach I am removing `print 'Getting upload URL...'` as it breaks abstraction in a major way and I do not think it is very important to communicate this to the user. We can add it back later if it is needed after all.

**Comment by bwbeach** [comment]
Sounds good.

**Comment by bwbeach** [comment]
How close are you on #11?  If you're close, I could wait on #20.

I'll go ahead an pull in #20 later today if I don't hear from you.

**Comment by ppolewicz** [comment]
I am close. I will finish tonight.
Changes in `upload_file` are are hard. Everything is glued together to everything in there.

It is my fault that #20 will have conflicts and I can see that you intend to merge it in, so in order to avoid putting additional burden on @cederberg, I will try to use git magic to merge it and resolve the conflicts myself. It has to be in the right order with my commits or otherwise the conflict will be massive.

**Comment by ppolewicz** [comment]
@bwbeach there is code to cope with the fact that the API has returned a dictionary after uploading a file, but the dictionary did not contain the `fileId` key. I suspect that an early version of b2 api did that. Can I remove it now and assume `fileId` will be returned properly?

**Comment by bwbeach** [comment]
I think that was an unclear way of checking whether an error was returned, but there are better checks for it now.  Feel free to remove it and clean up the code.

**Comment by bwbeach** [comment]
I'll wait until you're done.

- BrianB

**Comment by ppolewicz** [comment]
I started work on `upload_file`, which required refactoring of error handling, which required refactoring of retry mechanic, which required refactoring of OpenUrl, and so on. One thing led to another and according to `git diff --stat`, 465 LOC were added/deleted. It is 2 AM and my programming skills are getting weaker.

IMO it is not a good idea to merge those new changes with the previous changes. Therefore lets execute plan B: **merge it as it currently** is and do the remaining items in other pull requests.

I will coordinate the merging and testing of #20 in its pull request.

**Comment by ppolewicz** [comment]
just a moment, test failure

**Comment by ppolewicz** [comment]
It was a bad git add, I fixed it. Ready for merge.

**Pull request merged**
