### PR TITLE
remove python 2.6 dependency and update arrow version.

### LINKED ISSUE #551: Arrow dependency restrictions prohibiting updates of B2
The arrow package is now at version 0.13.0. B2 has a restriction of no greater than 0.12.1. This is preventing B2 from upgrading with an update of all outdated pip packages. Can we dependency updated in B2?

Reference: https://github.com/crsmithdev/arrow/releases

### PR DESCRIPTION
**Pull request by sww1235**
Aimed to fix #551

### CODE REVIEW

**Comment by sww1235** [comment]
looks like the two failing tests in travis are caused by YAPF, which I can easily change, but was unclear if I should pollute this pull request with unrelated issues

**Comment by ppolewicz** [comment]
The repository is being split in half right now, please try to make PRs as small as possible.

**Comment by sww1235** [comment]
I am unclear what could be smaller about this pull request.

If you want to wait to merge until after the repo split happens, let me know and I can rebase after the split

**Comment by ppolewicz** [comment]
I meant to avoid adding changes done by YAPF into this PR.

**Comment by sww1235** [comment]
I did not run YAPF on this since I only modified one line of actual python code. I did manually change b2http.py which I can revert if that would be preferable.

**Comment by ppolewicz** [comment]
The split is nearing completion and this PR is very small. Lets merge it after the split.

**Comment by sww1235** [comment]
That will be fine

**Comment by sww1235** [comment]
Rebased on newest master after split repo commits.

**Pull request merged**
