### PR TITLE
Add a progress bar

### PR DESCRIPTION
**Pull request by ppolewicz**

### CODE REVIEW

**Comment by ppolewicz** [comment]
@bwbeach if there is a pep8 violation (or some other problem), please raise it in review and ask me to fix it rather than fix it yourself. This way I can learn (and you can scale much better)!

**Comment by bwbeach** [comment]
Will do.  Thanks.

I've started using the free, community edition of PyCharm, which includes PEP 8 warnings.

**Comment by ppolewicz** [comment]
If you don't mind some CI, I'll add automatic verification of such things for this project after I complete #11.

**Comment by bwbeach** [comment]
Sounds good.

I added a test program, but it needs account credentials to run, and I didn't want to make those public.

**Pull request merged**
