### PR TITLE
List Bucket from allowed field only (if specified)

### PR DESCRIPTION
**Pull request by spartan218**
This is the fix for allowing us to make the CLI calls which require list buckets specifically when we have an application key that is restricted to a bucket.

### CODE REVIEW

**Comment by ppolewicz** [comment]
Could you please add a test?

**Comment by spartan218** [comment]
Yes, I was just telling Brian I should add a test.
Trying to decide whether or not to put the test in test_console_tool.py or make it 
a part of the integration tests. Thoughts @ppolewicz?

**Comment by bwbeach** [comment]
We need both kinds of tests.  There should be a unit test that covers this, as well as a few integration tests that cover app keys and restricted app keys.  The integration tests don't need to cover all commands; the handling of app keys is not command specific.

**Comment by ppolewicz** [comment]
I am talking to Codacy support about `Codacy was unable to analyse your pull request.`

also, Travis doesn't seem to have triggered here, I think due to missed hook, so it was a transient error and will resolve by itself when the branch is updated in any way. Hopefully...

**Comment by spartan218** [comment]
Testing now included with some other small fixes we found along the way.

**Pull request merged**
