### PR TITLE
CLI functionality

### PR DESCRIPTION
**Pull request by dparamonov-reef**

### CODE REVIEW

**Comment by ppolewicz** [comment]
This is a part of #547

**Comment by bwbeach** [comment]
Some context in the PR description would be good.

It looks like this is step 5 of #547: "remove SDK code from CLI, adding a dependency in the CLI from SDK instead".  So I assume we won't be merging this to B2_Command_Line_Tool master branch until steps 1 through 4 have been completed.

**Comment by bwbeach** [comment]
What's the strategy for testing that client code using the SDK from the existing `b2` package will continue to work, and be able to import the same things?

**Comment by ppolewicz** [comment]
The plan outlined in #547 outdated quickly during implementation. The plan is to have one PR to the sdk repository and 3 PRs to CLI:

1. #550 with removing the SDK code
1. Next one to add warnings when someone attempts to import a sdk class from the CLI package
1. Another one to add tests which check if it's possible to import sdk classes from cli and to make sure that warnings are properly emitted if such import is attempted, but not when the ConsoleTool class is imported (as someone might want to subclass that and it shouldn't trigger a warning)

The scope of those 3 PRs was separated like that to make it easier to review.

**Comment by bwbeach** [comment]
So this PR will not be merged until the SDK is in place and available on PyPI?

**Comment by bwbeach** [comment]
Would it make sense to reorder the steps, so that client code using the SDK and importing it from the CLI package will continue to work with `master`?

1. Add tests for importing SDK classes from the CLI.
2. Switch CLI to use the SDK instead of the its own implementation.
3. Remove the SDK classes from the CLI.

**Comment by ppolewicz** [comment]
> So this PR will not be merged until the SDK is in place and available on PyPI?
Correct, CI wouldn't pass otherwise.

> Would it make sense to reorder the steps (...)
If we have thought about those tests beforehand, then yes, that would be a very good plan. Unfortunately doing it now would require a lot of work due to a rebase impossible to resolve automatically. Therefore lets review the changes in the order they were done and just merge them all on the same day.

**Comment by bwbeach** [comment]
Merging all at the same time will work.

**Pull request merged**
