### PR TITLE
Add sphinx source files

### PR DESCRIPTION
**Pull request by alextsui05**
This PR is in response to issue https://github.com/Backblaze/B2_Command_Line_Tool/issues/147

Actually, it is still a work in progress. I just wanted to get the ball rolling and start the discussion about what sort of things folks would like to see in the documentation.

## Overview

* Added Sphinx source files to automatically generate documentation pages from the source code.
* Because documentation is autogenerated, it's not committed to the repo, but for the sake of previewing and discussing the contents, I uploaded a temporary copy here: https://files.atsui.me/tmp/B2_Command_Line_Tool/17cb355/build/html/

## To-do List

- [ ] Discuss and figure out requirements for documentation

## Memo on Setup

Just for reference, these were the steps I took to set up the Sphinx source files.

0. `pip install sphinx` to install v1.6.4 of sphinx
1. Run `sphinx-quickstart` and configure the project
2. Run `sphinx-autodoc` to parse through the API modules and populate the documentation files

For reference, this is my terminal session for running `sphinx-quickstart`
```
$ sphinx-quickstart 
Welcome to the Sphinx 1.6.4 quickstart utility.

Please enter values for the following settings (just press Enter to
accept a default value, if one is given in brackets).

Enter the root path for documentation.
> Root path for the documentation [.]: 

You have two options for placing the build directory for Sphinx output.
Either, you use a directory "_build" within the root path, or you separate
"source" and "build" directories within the root path.
> Separate source and build directories (y/n) [n]: y

Inside the root directory, two more directories will be created; "_templates"
for custom HTML templates and "_static" for custom stylesheets and other static
files. You can enter another prefix (such as ".") to replace the underscore.
> Name prefix for templates and static dir [_]: 

The project name will occur in several places in the built documentation.
> Project name: B2_Command_Line_Tool
> Author name(s): Backblaze

Sphinx has the notion of a "version" and a "release" for the
software. Each version can have multiple releases. For example, for
Python the version is something like 2.5 or 3.0, while the release is
something like 2.5.1 or 3.0a1.  If you don't need this dual structure,
just set both to the same value.
> Project version []: 0.7
> Project release [0.7]: 

If the documents are to be written in a language other than English,
you can select a language here by its language code. Sphinx will then
translate text that it generates into that language.

For a list of supported codes, see
http://sphinx-doc.org/config.html#confval-language.
> Project language [en]: 

The file name suffix for source files. Commonly, this is either ".txt"
or ".rst".  Only files with this suffix are considered documents.
> Source file suffix [.rst]: 

One document is special in that it is considered the top node of the
"contents tree", that is, it is the root of the hierarchical structure
of the documents. Normally, this is "index", but if your "index"
document is a custom template, you can also set this to another filename.
> Name of your master document (without suffix) [index]: 

Sphinx can also add configuration for epub output:
> Do you want to use the epub builder (y/n) [n]: n

Please indicate if you want to use one of the following Sphinx extensions:
> autodoc: automatically insert docstrings from modules (y/n) [n]: y
> doctest: automatically test code snippets in doctest blocks (y/n) [n]: n
> intersphinx: link between Sphinx documentation of different projects (y/n) [n]: y
> todo: write "todo" entries that can be shown or hidden on build (y/n) [n]: 
> coverage: checks for documentation coverage (y/n) [n]: 
> imgmath: include math, rendered as PNG or SVG images (y/n) [n]: 
> mathjax: include math, rendered in the browser by MathJax (y/n) [n]: 
> ifconfig: conditional inclusion of content based on config values (y/n) [n]: y
y
> githubpages: create .nojekyll file to publish the document on GitHub pages (y/n) [n]: n

A Makefile and a Windows command file can be generated for you so that you
only have to run e.g. `make html' instead of invoking sphinx-build
directly.
> Create Makefile? (y/n) [y]: y
> Create Windows command file? (y/n) [y]: n

Creating file ./source/conf.py.
Creating file ./source/index.rst.
Creating file ./Makefile.

Finished: An initial directory structure has been created.

You should now populate your master file ./source/index.rst and create other documentation
source files. Use the Makefile to build the docs, like so:
   make builder
where "builder" is one of the supported builders, e.g. html, latex or linkcheck.
```

The `sphinx-apidoc` command I ran from the root of the project directory was:

```
sphinx-apidoc -o doc/source b2
```

### CODE REVIEW

**Comment by bwbeach** [comment]
Thanks for getting this started!

This is something we've been wanting to do for quite a while, but haven't had the time.  (And I don't have the Sphinx expertise.)

I'm in favor of merging this pull request once the build issue is fixed.

**Comment by bwbeach** [comment]
OK.  I finally had time to look at the build issues.  The appveyor issue should be fixed if you merge from master.

The problem in Travis is python formatting.  In this project, we use yapf to ensure consistent formatting.  If you run the `pre-commit.sh` script, it will make a few minor changes to `doc/source/conf.py`, and then I think the builds will be happy.

**Comment by alextsui05** [comment]
@bwbeach Thanks for the pointer, I'll make a note to run that before committing. I went ahead and ran yapf and updated the branch, but it now seems like there's an error in setting up the build environment.

**Comment by bwbeach** [comment]
Looks like the problem is the copyright check, which insists that all `.py` files contain the string `All Rights Reserved`.

Buried in the build output is this message:

```
license is missing from:
      1 doc/source/conf.py
```

I think that if you add a copyright to that file, it will be happy.  Copying one from the other source files would work.

**Comment by alextsui05** [comment]
@bwbeach Thanks, that did the trick ✅ 

Also, would you prefer the commits squashed into one?

**Comment by bwbeach** [comment]
Don't care about multiple commits.  I'll go ahead and merge.

**Pull request merged**
