### PR TITLE
Option to ignore modification time

### PR DESCRIPTION
**Pull request by svonohr**
As discussed in #151.
It's still missing tests for the new option.

### CODE REVIEW

**Comment by svonohr** [comment]
What needs to be in the doc string?

**Comment by bwbeach** [comment]
The doc string for `sync` should mention the `--compareVersions` option, say what it does, what the three choices are, and what the default is.

**Comment by svonohr** [comment]
I think I did that in the second commit. Or did I miss some doc strings?

**Comment by bwbeach** [comment]
Looks good.  Sorry I missed that.

**Comment by svonohr** [comment]
This should be ready for merging into master.

**Comment by ppolewicz** [comment]
LGTM

**Pull request merged**
