### PR TITLE
Notarize the app for macOS

### PR DESCRIPTION
**Pull request by mlech-reef**

### CODE REVIEW

**Comment by mlech-reef** [comment]
@mpnowacki-reef do you know what is going on with CI and the failing encryption test?

**Comment by mpnowacki-reef** [comment]
the notarization doesn't seem to work. I made a branch with the new `deploy-bundle` in CI to test it: https://github.com/Backblaze/B2_Command_Line_Tool/pull/710

After downloading the binary i get the usual behaviour: a severe warning that I have to bypass in "Security & Privacy" and then a onetime warning. After i accept the second the binary works fine over and over.
Screenshot 2021-05-10 at 11 11 12
Screenshot 2021-05-10 at 11 12 55

**Review by ooola — APPROVED** [review]
ship it!

**Comment by mpnowacki-reef** [comment]
I've tested it and it works

**Review by mpnowacki-reef — APPROVED** [review]

**Pull request merged**
