### PR TITLE
Call for pylint

### PR DESCRIPTION
**Pull request by szepeviktor**
Let's see what pylint has to say.

### CODE REVIEW

**Comment by szepeviktor** [comment]
In the Travis log: https://travis-ci.org/Backblaze/B2_Command_Line_Tool/jobs/171681078#L408

**Comment by szepeviktor** [comment]
We have a permissive `|| true`.

**Comment by ppolewicz** [comment]
We run pylint via Codacy, which aggregates various checkers from various pylint-like tools. It also allows us to store suppresions on their server, so our code is not littered with it.

Default pylint configuration is horrible. It spews out garbage like "not enough methods in a class" and "missing docstring". We have adjusted the configuration in Codacy accordingly and we use it on regular basis. For code formatting we use yapf.

I am against merging this and running `pylint` twice, so that one result can be ignored. Shall we close it?

**Comment by szepeviktor** [comment]
OK, I see.
https://www.codacy.com/app/b2_command_line_tool/B2_Command_Line_Tool/issues/ignored

**Comment by szepeviktor** [comment]
Not even this *error*?
`console_tool.py:862,70: Class 'Command' has no '__subclasses__' member (no-member)`

**Comment by ppolewicz** [comment]
No.

**Pull request closed without merging**
